version: '3.4'
services:
  xdai.avado.dnp.dappnode.eth:
    image: 'xdai.avado.dnp.dappnode.eth:1.0.3'
    build: ./build
    volumes:
      - 'data:/home/openethereum/.local/share/io.parity.ethereum'
    ports:
      - 30305
      - 8545
      - 30305/udp
    restart: always
    environment:
      - EXTRA_OPTS=
volumes:
  data: {}
