version: '3.4'
services:
  xdai.avado.dnp.dappnode.eth:
    image: 'xdai.avado.dnp.dappnode.eth:1.0.5'
    build: ./build
    volumes:
      - 'data:/root/.local'
    ports:
      - '30305:30305'
      - '30305:30305/udp'
    restart: always
    environment:
      - EXTRA_OPTS=
volumes:
  data: {}
